---
- name: Enable the backports repository
  apt_repository:
    repo: 'deb http://ftp.debian.org/debian wheezy-backports main'
    state: present
    update_cache: true

- name: download certbot
  command: "wget https://dl.eff.org/certbot-auto"
  args:
    chdir: /usr/local/sbin
    creates: /usr/local/sbin/certbot-auto
    warn: false

- name: Make certbot-auto executable
  file:
    path: /usr/local/sbin/certbot-auto
    mode: 0700

- name: Create symlink from certbot-auto to certbot
  file:
    src: /usr/local/sbin/certbot-auto
    dest: /usr/local/sbin/certbot
    owner: root
    group: root
    state: link

- name: First run of certbot-auto - takes a while
  command: "certbot --os-packages-only --quiet"
  args:
    creates: "/opt/eff.org/certbot/venv/bin/python"
  
# vim:ft=ansible:
